### Create new exam
POST http://127.0.0.1:8000/app/exams/
Content-Type: application/json

{
  "title": "Kolokwium",
  "start_date": "2024-12-01T17:00:00.000Z",
  "end_date": "2024-12-02T17:00:00.000Z",
  "duration_limit": 30,
  "status": "UNDEFINED",
  "course_realization_id": 2,
  "questions_quantity": 0,
  "max_points": 20,
  "type": "TEST"
}

### Get all exams
GET http://127.0.0.1:8000/app/exams/all

### Get exam
GET http://127.0.0.1:8000/app/exams/1

### Update exam
PUT http://127.0.0.1:8000/app/exams/1
Content-Type: application/json

{
  "title": "Sprawdzian",
  "start_date": "2024-12-01T17:00:00.000Z",
  "end_date": "2024-12-02T17:00:00.000Z",
  "duration_limit": 30,
  "status": "UNDEFINED",
  "course_realization_id": 2,
  "questions_quantity": 0,
  "max_points": 20,
  "type": "TEST"
}

### Delete exam
DELETE http://127.0.0.1:8000/app/exams/1
