### Create new user (student)
POST http://127.0.0.1:8000/app/users/
Content-Type: application/json

{
    "name": "Tomasz",
    "surname": "Złomiarz",
    "role": "STUDENT",
    "index": 310035,
    "email": "student@gmail.com",
    "password": "student"
}

### Create new user (lecturer)
POST http://127.0.0.1:8000/app/users/
Content-Type: application/json

{
    "name": "Jurek",
    "surname": "Ogórek",
    "role": "LECTURER",
    "email": "lecturer@gmail.com",
    "password": "lecturer"
}

### Create new user (lecturer)
POST http://127.0.0.1:8000/app/users/
Content-Type: application/json

{
    "name": "Karolina",
    "surname": "Malina",
    "role": "LECTURER",
    "email": "malina@gmail.com",
    "password": "malina"
}



### Create new course
POST http://127.0.0.1:8000/app/courses/
Content-Type: application/json

{
    "title": "Algorytmy i struktury danych",
    "shortcut": "AISDI"
}

### Create new course
POST http://127.0.0.1:8000/app/courses/
Content-Type: application/json

{
    "title": "Analiza i projektowanie systemów informacyjnych",
    "shortcut": "APSI"
}

### Create new course
POST http://127.0.0.1:8000/app/courses/
Content-Type: application/json

{
    "title": "Bazy danych 2",
    "shortcut": "BD2"
}

### Create new course
POST http://127.0.0.1:8000/app/courses/
Content-Type: application/json

{
    "title": "Sieci komputerowe",
    "shortcut": "SKM"
}

### Create new course
POST http://127.0.0.1:8000/app/courses/
Content-Type: application/json

{
    "title": "Nanotechnologie",
    "shortcut": "NAN"
}

### Create new course
POST http://127.0.0.1:8000/app/courses/
Content-Type: application/json

{
    "title": "Programowanie obiektowe",
    "shortcut": "PROI"
}

### Create new course
POST http://127.0.0.1:8000/app/courses/
Content-Type: application/json

{
    "title": "Podstawy automatyki",
    "shortcut": "PODA"
}



### Create new course_realization
POST http://127.0.0.1:8000/app/course_realizations/
Content-Type: application/json

{
    "semester": "24L",
    "course_id": 3,
    "lecturer_id": 3
}


### Create new course_realization
POST http://127.0.0.1:8000/app/course_realizations/
Content-Type: application/json

{
    "semester": "24Z",
    "course_id": 1,
    "lecturer_id": 2
}

### Create new course_realization
POST http://127.0.0.1:8000/app/course_realizations/
Content-Type: application/json

{
    "semester": "24Z",
    "course_id": 2,
    "lecturer_id": 3
}

### Create new course_realization
POST http://127.0.0.1:8000/app/course_realizations/
Content-Type: application/json

{
    "semester": "23Z",
    "course_id": 5,
    "lecturer_id": 3
}

### Create new course_realization
POST http://127.0.0.1:8000/app/course_realizations/
Content-Type: application/json

{
    "semester": "23Z",
    "course_id": 6,
    "lecturer_id": 3
}

### Create new course_realization
POST http://127.0.0.1:8000/app/course_realizations/
Content-Type: application/json

{
    "semester": "22Z",
    "course_id": 7,
    "lecturer_id": 3
}


### Create new exam
POST http://127.0.0.1:8000/app/exams/
Content-Type: application/json

{
  "title": "Sprawdzian 1",
  "start_date": "2024-12-06T17:00:00.000Z",
  "end_date": "2024-12-12T17:00:00.000Z",
  "duration_limit": 30,
  "status": "SCHEDULED",
  "course_realization_id": 3,
  "questions_quantity": 0,
  "max_points": 20,
  "type": "TEST"
}

### Create new exam
POST http://127.0.0.1:8000/app/exams/
Content-Type: application/json

{
  "title": "Kolokwium",
  "start_date": "2024-12-12T17:00:00.000Z",
  "end_date": "2024-12-14T17:00:00.000Z",
  "duration_limit": 60,
  "status": "CLOSED",
  "course_realization_id": 3,
  "questions_quantity": 0,
  "max_points": 20,
  "type": "TEST"
}

### Create new exam
POST http://127.0.0.1:8000/app/exams/
Content-Type: application/json

{
  "title": "Kolokwium - modele",
  "start_date": "2024-12-22T17:00:00.000Z",
  "end_date": "2024-12-22T17:00:00.000Z",
  "duration_limit": 45,
  "status": "ACTIVE",
  "course_realization_id": 3,
  "questions_quantity": 0,
  "max_points": 20,
  "type": "TEST"
}

### Create new exam
POST http://127.0.0.1:8000/app/exams/
Content-Type: application/json

{
  "title": "Projekt",
  "start_date": "2024-11-11T17:00:00.000Z",
  "end_date": "2024-12-11T17:00:00.000Z",
  "duration_limit": 43200,
  "status": "ACTIVE",
  "course_realization_id": 3,
  "max_points": 15,
  "type": "PROJECT"
}

### Create new question
POST http://127.0.0.1:8000/app/questions/
Content-Type: application/json

{
  "text": "Zaznacz elementy charakterystyczne dla modelu relacyjnego.",
  "image": null,
  "type": "MULTI",
  "score": 3,
  "score_type": "PROPORTIONAL",
  "exam_id": 1
}

### Create new question
POST http://127.0.0.1:8000/app/questions/
Content-Type: application/json

{
  "text": "Napisz zalety bazy danych Oracle.",
  "image": null,
  "type": "OPEN",
  "score": 5,
  "score_type": "FULL",
  "exam_id": 1
}

### Create new question item
POST http://127.0.0.1:8000/app/question_items/
Content-Type: application/json

{
  "text": "Relacja",
  "image": null,
  "correctness": true,
  "question_id": 1
}

### Create new question item
POST http://127.0.0.1:8000/app/question_items/
Content-Type: application/json

{
  "text": "Encja",
  "image": null,
  "correctness": false,
  "question_id": 1
}

### Create new question item
POST http://127.0.0.1:8000/app/question_items/
Content-Type: application/json

{
  "text": "Tabela",
  "image": null,
  "correctness": true,
  "question_id": 1
}

### Create new exam student
POST http://127.0.0.1:8000/app/exam_students/
Content-Type: application/json

{
  "score": null,
  "status": "INACTIVE",
  "start_date": null,
  "end_date": null,
  "duration": null,
  "exam_id": 1,
  "student_id": 1
}

### Create new exam student
POST http://127.0.0.1:8000/app/exam_students/
Content-Type: application/json

{
  "score": null,
  "status": "INACTIVE",
  "start_date": null,
  "end_date": null,
  "duration": null,
  "exam_id": 1,
  "student_id": 1
}

### Create new exam student
POST http://127.0.0.1:8000/app/exam_students/
Content-Type: application/json

{
  "score": 12.12,
  "status": "COMPLETED",
  "start_date": "2024-12-06T17:00:00.000Z",
  "end_date": "2024-12-12T17:00:00.000Z",
  "duration": 22,
  "exam_id": 2,
  "student_id": 1
}

### Create new exam student
POST http://127.0.0.1:8000/app/exam_students/
Content-Type: application/json

{
  "score": null,
  "status": "ACTIVE",
  "start_date": null,
  "end_date": null,
  "duration": null,
  "exam_id": 3,
  "student_id": 1
}

### Create new exam student
POST http://127.0.0.1:8000/app/exam_students/
Content-Type: application/json

{
  "score": null,
  "status": "ACTIVE",
  "start_date": null,
  "end_date": null,
  "duration": null,
  "exam_id": 4,
  "student_id": 1
}


### INSERT INTO `examination`.`students_course_realizations` (`student_id`, `course_realization_id`) VALUES (1, 1);
### INSERT INTO `examination`.`students_course_realizations` (`student_id`, `course_realization_id`) VALUES (1, 2);
### INSERT INTO `examination`.`students_course_realizations` (`student_id`, `course_realization_id`) VALUES (1, 3);
